### ISSUE TITLE
项目启动后访问报错，页面加载不出来

### ISSUE THREAD

**Issue by sjz192168** [yudaocode/yudao-ui-admin-vue3#108]
Uncaught Error: A route named "Redirect" has been added as a child of a route with the same name. Route names must be unique and a nested route cannot use the same name as an ancestor.

**Comment by JokerNineteen** [comment]
我也报这个错 搞不明白

**Comment by baymax55** [comment]
Redirect路由名称重复了，把重复的名称改一下就好

**Comment by gmxshow** [comment]
Error: A route named "Express" has been added as a child of a route with the same name. Route names must be unique and a nested route cannot use the same name as an ancestor.那个改了就报这个错了

**Comment by YunaiV** [comment]
已经修复。

**Comment by YLRK** [comment]
> Error: A route named "Express" has been added as a child of a route with the same name. Route names must be unique and a nested route cannot use the same name as an ancestor.那个改了就报这个错了

同样遇到这个问题，这个怎么修复啊
