### ISSUE TITLE
【欢迎贡献，可认领】该前端没有微信的扫码支付

### ISSUE THREAD

**Issue by MurphyZX** [yudaocode/yudao-ui-admin-vue3#19]
![image](https://github.com/yudaocode/yudao-ui-admin-vue3/assets/61101985/1ccd9a9f-e22f-44b6-a804-473ba69aa819)

但是vue2这个版本有
![image](https://github.com/yudaocode/yudao-ui-admin-vue3/assets/61101985/f9f710b6-51fe-443a-b6cd-2e63eb30a9db)

**Comment by YunaiV** [comment]
欢迎 pr 贡献下哈。
