### ISSUE TITLE
构建发布项目失败

### ISSUE THREAD

**Issue by jg-8** [yudaocode/yudao-ui-admin-vue3#21]
node_modules/.pnpm/@form-create+designer@3.1.4_vue@3.3.8/node_modules/@form-create/designer/dist/index.es.js (264:9) Use of eval in "node_modules/.pnpm/@form-create+designer@3.1.4_vue@3.3.8/node_modules/@form-create/designer/dist/index.es.js" is strongly discouraged as it poses security risks and may cause issues with minification.
Building [██████████████████████████░░░░░░░░░░░░░░] 65% | Time: 582.0sKilled
 ELIFECYCLE  Command failed with exit code 137.

不管是 build:pro/build:front ，都会出现上面的错误，导致无法完成。

**Comment by jg-8** [comment]
环境：
pnpm:8.10.4
npm: '9.6.3',
node: '19.9.0',

**Comment by YunaiV** [comment]
测试了，暂时没发现，建议自查下哈。
