### ISSUE TITLE
支持electron打包成exe吗！？？

### ISSUE THREAD

**Issue by lee2350** [yudaocode/yudao-ui-admin-vue3#23]
![微信图片_20240131144240](https://github.com/yudaocode/yudao-ui-admin-vue3/assets/157350459/a5269b92-7587-42e7-a6c3-9e245dc579c6)

今天用electron尝试了一下生成exe桌面应用 但是打开以后 登录界面一直在转圈，并且图片貌似获取不到

**Comment by YunaiV** [comment]
这块了解不多，目前解决了么？

有没具体啥报错哈？

**Comment by YunaiV** [comment]
由于木有回复，暂时关闭该 issue
