### ISSUE TITLE
npm install 编译项目，总是抛出以下异常，还请大佬多多指点，感谢

### ISSUE THREAD

**Issue by mychao** [yudaocode/yudao-ui-admin-vue3#28]
npm WARN tar TAR_ENTRY_INVALID checksum failure
npm WARN tar TAR_ENTRY_INVALID checksum failure
npm WARN tar TAR_ENTRY_INVALID checksum failure
npm WARN tar TAR_ENTRY_INVALID checksum failure
npm WARN tar TAR_ENTRY_INVALID checksum failure
npm WARN tar TAR_ENTRY_INVALID checksum failure
npm WARN tar TAR_ENTRY_INVALID checksum failure
npm WARN tar TAR_ENTRY_INVALID checksum failure
npm WARN tar zlib: incorrect data check
npm WARN tarball tarball data for element-plus@https://registry.npmmirror.com/element-plus/-/element-plus-2.5.3.tgz (sha512-wmtstxaMkD6UinIgD+45CjrhbRh4u0vt+/GgxfPeMLt5pDpIVwZFjkUaVcWqqxcxd5a80HP3XlDF74fW7wim9A==) seems to be corrupted. Trying again.
npm WARN tar zlib: incorrect data check
npm WARN tarball tarball data for element-plus@https://registry.npmmirror.com/element-plus/-/element-plus-2.5.3.tgz (sha512-wmtstxaMkD6UinIgD+45CjrhbRh4u0vt+/GgxfPeMLt5pDpIVwZFjkUaVcWqqxcxd5a80HP3XlDF74fW7wim9A==) seems to be corrupted. Trying again.
npm WARN tar zlib: incorrect data check
npm WARN tarball tarball data for @iconify/json@https://registry.npmmirror.com/@iconify/json/-/json-2.2.187.tgz (sha512-s2YGP9Nuz1x4xAQq78Y6TZFqGZ8wUO7YlOdbqjwoMgmwJPhEhUrxLs2S17im1rG5g9TzAQsYzt4vsSlgCmoKDA==) seems to be corrupted. Trying again.
npm WARN tarball tarball data for @iconify/json@https://registry.npmmirror.com/@iconify/json/-/json-2.2.187.tgz (sha512-s2YGP9Nuz1x4xAQq78Y6TZFqGZ8wUO7YlOdbqjwoMgmwJPhEhUrxLs2S17im1rG5g9TzAQsYzt4vsSlgCmoKDA==) seems to be corrupted. Trying again.
npm ERR! code ENOENT
npm ERR! syscall stat
npm ERR! path /Users/admin/.npm/_cacache/content-v2/sha512/b3/66/063fd36ecf5c78c4042aefc63a4d916a199f3050eed894e75baa3c283209b024f844854af12ecd92d7b8a6d6b1b983d4f3010b18cede2fb129600a6a0a0c
npm ERR! errno -2
npm ERR! enoent ENOENT: no such file or directory, stat '/Users/admin/.npm/_cacache/content-v2/sha512/b3/66/063fd36ecf5c78c4042aefc63a4d916a199f3050eed894e75baa3c283209b024f844854af12ecd92d7b8a6d6b1b983d4f3010b18cede2fb129600a6a0a0c'
npm ERR! enoent This is related to npm not being able to find a file.
npm ERR! enoent

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/admin/.npm/_logs/2024-03-02T09_52_08_449Z-debug-0.log
npm ERR!     /Users/admin/.npm/_logs/2024-03-02T09_52_08_449Z-debug-1.log

**Comment by YunaiV** [comment]
https://doc.iocoder.cn/quick-start-front/

使用 pnpm install 噢

文档要认真阅读呀。
