### ISSUE TITLE
感谢大佬的贡献

### ISSUE THREAD

**Issue by quliting** [yudaocode/yudao-ui-admin-vue3#32]
我是net core 开发，用net写后端，想做一个ERP，想采用大佬的UI框架，
![image](https://github.com/yudaocode/yudao-ui-admin-vue3/assets/14035957/df14f9e2-5de3-4d36-87cb-c5cc8d0ba3cd)

文档和实际的有出入，是我入口不对吗？感谢

**Comment by YunaiV** [comment]
演示环境，暂时没部署最新的。

本地部署下就好了。
