### ISSUE TITLE
为啥 TokenAuthenticationFilter 中使用的是 Google Guava 本地缓存，Gateway 集群多实例部署下是否命中率低？

### ISSUE THREAD

**Issue by gotoworld** [yudaocode/yudao-ui-admin-vue3#33]
不理解为啥不使用 社区常用的 Redis 分布式缓存Session方案？ 担心性能？ 

![image](https://github.com/yudaocode/yudao-ui-admin-vue3/assets/8605471/e54b1325-7fc6-4193-a09f-da8c4d573dcd)

**Comment by YunaiV** [comment]
提升网关性能

多实例的话，大多数公司，gateway 数量不会太多吧
