### ISSUE TITLE
routerHelper中generateRoute返回路由name设置错误，多个路由相同组件名/路径重名只能加载最后一个

### ISSUE THREAD

**Issue by JehChenxx** [yudaocode/yudao-ui-admin-vue3#34]
routerHelper中generateRoute定义路由如下：    
```JavaScript
// 路由地址转首字母大写驼峰，作为路由名称，适配keepAlive
    let data: AppRouteRecordRaw = {
      path: route.path,
      name:
        route.componentName && route.componentName.length > 0
          ? route.componentName
          : toCamelCase(route.path, true),
      redirect: route.redirect,
      meta: meta
    }
```
其中name不应由componentName或当前路由的路径设置，会导致不同父目录下无法存在相同组件或路径。
如学生+老师下均有个人信息路径userInfo+组件UserInfo，应当可以实现组件上区分Teacher/UserInfo和Student/UserInfo+路径上区分teacher/userInfo和student/userInfo。
name应单独设置输入框，或使用父路由下组件/路径拼接

**Comment by YunaiV** [comment]
这个，建议组件名定义唯一。。。

**Comment by JehChenxx** [comment]
> 这个，建议组件名定义唯一。。。

界面没有提示唯一性，也没有表明组件名将作为路由name，虽然组件名唯一可以避免此情况，但毕竟是隐式的规则，不合理。

如果界面上是“路由名称”的输入框，或者增加提示将作为“路由名称”，那还是可以假设开发者应当知晓路由名称不可重复，但是“组件名”。。。很难理解

**Comment by YunaiV** [comment]
这个还好哈。大多数前端框架，都是做了这样要求的哈。
