### ISSUE TITLE
编译打包之后，出现error

### ISSUE THREAD

**Issue by fish8848-chen** [yudaocode/yudao-ui-admin-vue3#38]
请问这个问题，是由于什么问题导致的呢？我本地npm run build:dev之后，发到服务器上，然后就报错了
<img width="1332" alt="企业微信截图_bea59a63-fee2-4aae-bc26-56cc90bf368d" src="https://github.com/yudaocode/yudao-ui-admin-vue3/assets/32054096/3344cb10-bb69-4b84-890d-5eec02be6387">

**Comment by fish8848-chen** [comment]
..

**Comment by YunaiV** [comment]
拉下最新代码，已经修复，有个 erchart 使用不对
