### ISSUE TITLE
【功能优化】建议商品类别的操作栏新增 "查看商品" 功能

### ISSUE THREAD

**Issue by DevDengChao** [yudaocode/yudao-ui-admin-vue3#40]
调试商品类别时发现无法删除部分商品类别, 但是当前页面又没有快捷方式可以查询该类别下有哪些商品, 必须手动前往商品列表, 并筛选指定类别才能知道有哪些商品在这个分类里.

建议新增一个 "查看商品" 的操作, 点击后在新的 "商品列表" 标签页中自动筛选对应类别的商品.

**Comment by YunaiV** [comment]
可以的，有兴趣 pull request 贡献下么？

**Comment by DevDengChao** [comment]
有参考么？前几天尝试基于请求路径上的参数去实现但是似乎有些数据同步方面的问题不太好处理。

**Comment by YunaiV** [comment]
你看下，定时任务的日志

**Comment by YunaiV** [comment]
https://gitee.com/yudaocode/yudao-ui-admin-vue3/commit/36b5db16dd1b0cd4beaeffd0a927ff43868a65ee
