### ISSUE TITLE
【功能优化】添加商品属性时无法筛选已有的商品属性

### ISSUE THREAD

**Issue by DevDengChao** [yudaocode/yudao-ui-admin-vue3#43]
![image](https://github.com/yudaocode/yudao-ui-admin-vue3/assets/16363180/3ac435b7-3760-4f09-830c-0d3d4de1e945)

这里应当允许用户通过下拉菜单的方式选择已有的商品属性的, 不然每次都让管理员输入属性名称, 容易误导管理员每次都创建了新的商品属性.

**Comment by YunaiV** [comment]
不错的建议，有没兴趣 pull request 下好。

**Comment by DevDengChao** [comment]
两周内不会考虑发pr😂

**Comment by YunaiV** [comment]
合并到 https://github.com/yudaocode/yudao-ui-admin-vue3/issues/47
