### ISSUE TITLE
【欢迎认领】添加商品时应当在提交前将待提交的内容缓存起来

### ISSUE THREAD

**Issue by DevDengChao** [yudaocode/yudao-ui-admin-vue3#46]
添加商品需要填写大量的内容, 但目前在切换页签时会导致已填写待提交的内容完全丢失, 极其影响体验.

建议在待提交时将已填写的内容缓存到 LocalStorage , 并在重新进入添加商品页签时尝试从中恢复待提交的内容, 提交完成后清除缓存.

**Comment by YunaiV** [comment]
这块，应该是个“bug”

商品编辑界面，没支持 vue keepalive。

感受上，修复这个可能会更好

**Comment by YunaiV** [comment]
https://gitee.com/yudaocode/yudao-ui-admin-vue3/commit/df8b1fbc0de57e556d03fba2ab7f82619ca239d3

目前是在新增的时候，增加一个 keepalive
修改的时候，因为后端有存储，所以先不 keepalive
