### ISSUE TITLE
【功能优化】添加商品属性时允许选择已有的属性值

### ISSUE THREAD

**Issue by DevDengChao** [yudaocode/yudao-ui-admin-vue3#47]
![image](https://github.com/yudaocode/yudao-ui-admin-vue3/assets/16363180/83292e30-ba87-49e8-b575-52c53d95403e)

选中已有属性值的属性时, 应当在合适的位置展示可供选择的已有属性值, 以便管理员能快速的填写属性.

**Comment by YunaiV** [comment]
不错的建议，有兴趣 pull request 下么？

**Comment by DevDengChao** [comment]
两周内不考虑发pr😂

**Comment by YunaiV** [comment]
① 添加属性时，支持下拉选择。

![image](https://github.com/user-attachments/assets/0bcfb68d-8343-4364-bab4-61fe5766a00f)

**Comment by YunaiV** [comment]
② 选择属性值的时候，支持下拉选择

![image](https://github.com/user-attachments/assets/e45ec2c0-a65f-4e62-a1d7-327241992c4e)
