### ISSUE TITLE
dept/index.vue has a error

### ISSUE THREAD

**Issue by jasnzhuang** [yudaocode/yudao-ui-admin-vue3#5]
yudao-ui-admin-vue3/src/views/system/dept/index.vue

[plugin:vite-plugin-eslint] C:\dev\yudao-ui-admin-vue3\src\views\system\dept\index.vue
  54:14  error  Replace `␍⏎······v-loading="loading"␍⏎······:data="list"␍⏎······row-key="id"␍⏎······default-expand-all␍⏎······v-if="refreshTable"␍⏎····` with `·v-loading="loading"·:data="list"·row-key="id"·default-expand-all·v-if="refreshTable"`  prettier/prettier

**Comment by YunaiV** [comment]
已修复
