### ISSUE TITLE
【欢迎认领】支付通道异步回调内容过长时内容超出弹窗范围

### ISSUE THREAD

**Issue by DevDengChao** [yudaocode/yudao-ui-admin-vue3#51]
![image](https://github.com/yudaocode/yudao-ui-admin-vue3/assets/16363180/51fc3a96-d736-4ee1-bb65-0b94377af736)

建议改进 div 的样式.

**Comment by YunaiV** [comment]
可以的哈。

**Comment by YunaiV** [comment]
https://gitee.com/yudaocode/yudao-ui-admin-vue3/commit/8bbe9ad424a113fff8fdb905d0773da42bb334de

已修复
