### ISSUE TITLE
收银台应当显示的提醒开发者去配置 "示例应用" 的支付渠道

### ISSUE THREAD

**Issue by DevDengChao** [yudaocode/yudao-ui-admin-vue3#52]
![image](https://github.com/yudaocode/yudao-ui-admin-vue3/assets/16363180/c6da0943-1e04-4a5f-a291-8ea8fd394d80)

目前的界面无法引导用户去完善 "示例应用" 中的支付渠道.
可以考虑添加显眼的文案提示, 或者将暂不可用的支付渠道设为被禁用状态加以引导.

**Comment by YunaiV** [comment]
这个，可能在支付应用那看一眼，就知道啦。

暂时不增加这个界面的复杂性哈。

**Comment by YunaiV** [comment]
谢谢建议哈
