### ISSUE TITLE
【性能优化】打包所需内存过大

### ISSUE THREAD

**Issue by mztlive** [yudaocode/yudao-ui-admin-vue3#55]
有没有人和你们反馈过，这个项目打包的时候要8G内存，这么大的内存要求16G的电脑根本跑不动啊

**Comment by YunaiV** [comment]
https://github.com/yudaocode/yudao-ui-admin-vue3/blob/master/package.json#L12

可以改动成 4G 或者其它。

我们主要用服务器打包，以及服务器打包怎么可以更快
