### ISSUE TITLE
【欢迎认领】测试 S3 存储桶成功时的对话框无法完全展示其中的文本内容

### ISSUE THREAD

**Issue by DevDengChao** [yudaocode/yudao-ui-admin-vue3#57]
![image](https://github.com/yudaocode/yudao-ui-admin-vue3/assets/16363180/852260c7-26b0-438e-a8be-20dbca7eedc0)

**Comment by YunaiV** [comment]
好的，UI 上的 bug

可以复制的哈。

**Comment by justinzhuying** [comment]
能不能完善一下文档里面对于自搭建的minio服务的说明模块

**Comment by YunaiV** [comment]
已修复

https://gitee.com/yudaocode/yudao-ui-admin-vue3/commit/3fec45b5b4c56d996639b535203a92442acc2c4a
