### ISSUE TITLE
2.2.0启动错误

### ISSUE THREAD

**Issue by siqn3046** [yudaocode/yudao-ui-admin-vue3#70]
15:27:31 [vite] Internal server error: Cannot find package 'E:\yudao-code\vue3\yudao-ui-admin-vue3-master\yudao-ui-admin-vue3-master\node_modules\.pnpm\@vitejs+plugin-vue-jsx@3.1.0_vite@5.1.4_@types+node@20.12.7_sass@1.75.0_terser@5.30.4__vue@3.4.21_typescript@5.3.3_\node_modules\@babel\plugin-transform-typescript\package.json' imported from E:\yudao-code\vue3\yudao-ui-admin-vue3-master\yudao-ui-admin-vue3-master\node_modules\.pnpm\@vitejs+plugin-vue-jsx@3.1.0_vite@5.1.4_@types+node@20.12.7_sass@1.75.0_terser@5.30.4__vue@3.4.21_typescript@5.3.3_\node_modules\@vitejs\plugin-vue-jsx\dist\index.cjs
Did you mean to import @babel+plugin-transform-typescript@7.24.4_@babel+core@7.24.4/node_modules/@babel/plugin-transform-typescript/lib/index.js?
  Plugin: vite:vue-jsx
  File: E:/yudao-code/vue3/yudao-ui-admin-vue3-master/yudao-ui-admin-vue3-master/src/components/FormCreate/src/components/useApiSelect.tsx

**Comment by siqn3046** [comment]
C:\Users\用户名\AppData\Local\Temp 清除文件夹后不报错了

**Comment by YunaiV** [comment]
好的哈。

应该是环境问题。

**Comment by sunzicheng** [comment]
![image](https://github.com/user-attachments/assets/c66cd174-7f90-46aa-8a6d-5835b351cbed)
我觉得应该是插件存在兼容性问题
