### ISSUE TITLE
[Vue warn] Write operation failed: computed value is readonly

### ISSUE THREAD

**Issue by jpdslmj** [yudaocode/yudao-ui-admin-vue3#74]
报了一堆：
[Vue warn] Write operation failed: computed value is readonly

setupAll | @ | main.ts:67
-- | -- | --
  | await in setupAll |   |  
  | (匿名) | @ | main.ts:70
  | setTimeout |   |  
  | (匿名) | @ | __uno.css:19
  | (匿名) | @ | __uno.css:19

**Comment by YunaiV** [comment]
测试了下，暂时没碰到，可以自查下，或者提供更多信息哈。
