### ISSUE TITLE
在线演示页面登录不了 是什么问题呢

### ISSUE THREAD

**Issue by akaxie** [yudaocode/yudao-ui-admin-vue3#76]
![007](https://github.com/user-attachments/assets/2be92645-18d6-4ca1-8ac3-c525884dadc9)
在线演示http://dashboard-vue3.yudao.iocoder.cn/login?redirect=/index 登录不了 是什么问题啊，大佬

**Comment by YunaiV** [comment]
服务器维护中。

**Comment by akaxie** [comment]
> 服务器维护中。

大概几时能恢复哇？

**Comment by mtgq** [comment]
> 服务器维护中。

维护多久啊？
