### ISSUE TITLE
演示地址登录失败

### ISSUE THREAD

**Issue by cloydlau** [yudaocode/yudao-ui-admin-vue3#79]
<img width="611" alt="image" src="https://github.com/user-attachments/assets/ff737b73-1e11-4db2-89a2-3fbfc0ccb01c">

**Comment by YunaiV** [comment]
服务器维护中，请耐心等待。

https://doc.iocoder.cn/

建议自行搭建下哈。

**Comment by cloydlau** [comment]
自己搭建了的哈，但是这个是演示地址，主要是发现有 bug 想提 pr，准备在演示地址做复现（自己搭建的那个有代码改动，为了确保 bug 在原代码中就存在，必须使用演示地址来复现）。

**Comment by YunaiV** [comment]
恩恩，你本地搭建了，有 pr 直接提，我会跟的呢！
