### ISSUE TITLE
构建报错，提示cjs不支持

### ISSUE THREAD

**Issue by mobf-kanyun** [yudaocode/yudao-ui-admin-vue3#83]
构建时提示错误，麻烦大佬帮忙看看～
npm run build:test

> my-web-admin@2.2.0-snapshot build:test
> node --max_old_space_size=8192 ./node_modules/vite/bin/vite.js build --mode test

The CJS build of Vite's Node API is deprecated. See https://vitejs.dev/guide/troubleshooting.html#vite-cjs-node-api-deprecated for more details.
Building [█████████████████████░░░░░░░░░░░░░░░░░░░] 52% | Time: 16.2s
Build failed. Please check the error message

error during build:
SyntaxError: Element is missing end tag.
    at createCompilerError (/Users/wang/work/newworld/my-web/my-web-admin/node_modules/.pnpm/@vue+compiler-core@3.4.21/node_modules/@vue/compiler-core/dist/compiler-core.cjs.prod.js:1325:17)

**Comment by mobf-kanyun** [comment]
原项目没有问题，是我改动出了问题，抱歉。

**Comment by mobf-kanyun** [comment]
原项目没有问题，是我改动出了问题，抱歉。

**Comment by YunaiV** [comment]
好的。这个一般是 vue 标签哪里没写对。。。
