### ISSUE TITLE
积木报表点击新建出现报错

### ISSUE THREAD

**Issue by Ldd1234567890** [yudaocode/yudao-ui-admin-vue3#88]
<img width="1133" alt="881f58eb_7893540" src="https://github.com/user-attachments/assets/db1e8994-6734-49ed-a874-876af289c46e">
<img width="1236" alt="1727259449234" src="https://github.com/user-attachments/assets/98ce837a-39cf-4d92-abdb-9ca694f0b2a6">

**Comment by YunaiV** [comment]
测试了下，暂时没碰到。

**Comment by Ldd1234567890** [comment]
兄弟，你测试的后端是微服务版本吗，前端vue3，积木报表设计新建报表后端没有报错，前端没有报500，就上面两张图片

**Comment by Ldd1234567890** [comment]
前端yudao-ui-admin-vue版本后端yudao-cloud版本

**Comment by Ldd1234567890** [comment]
我在新建积木报表的时候报错了
