### ISSUE TITLE
动态路由404

### ISSUE THREAD

**Issue by HuanYuanHe** [yudaocode/yudao-ui-admin-vue3#90]
![image](https://github.com/user-attachments/assets/8d511610-3c70-48da-874f-46574c6ae1d3)
![image](https://github.com/user-attachments/assets/a89afa98-bd8f-42cc-a8ab-1c9f8692cae6)
新配置了个页面，已经参照岗位管理配了路由，但是访问新菜单页面时候还是404，请问还需要哪里配置吗

**Comment by HuanYuanHe** [comment]
trade的index只修改了defineOptions({ name: 'SystemTrade' })

**Comment by YunaiV** [comment]
测试了下，暂时没碰到。

建议自查下哈。
